// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: rpc_service/auth_rpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthService_GenerateTokenByName_FullMethodName      = "/auth.AuthService/GenerateTokenByName"
	AuthService_GenerateTokenByEmail_FullMethodName     = "/auth.AuthService/GenerateTokenByEmail"
	AuthService_GenerateTokenByEmailCode_FullMethodName = "/auth.AuthService/GenerateTokenByEmailCode"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// 用户名密码登录
	GenerateTokenByName(ctx context.Context, in *AuthRequestByName, opts ...grpc.CallOption) (*AuthResponse, error)
	// 邮箱密码登录
	GenerateTokenByEmail(ctx context.Context, in *AuthRequestByEmail, opts ...grpc.CallOption) (*AuthResponse, error)
	// 邮箱验证码登录
	GenerateTokenByEmailCode(ctx context.Context, in *AuthRequestByEmailCode, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GenerateTokenByName(ctx context.Context, in *AuthRequestByName, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_GenerateTokenByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GenerateTokenByEmail(ctx context.Context, in *AuthRequestByEmail, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_GenerateTokenByEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GenerateTokenByEmailCode(ctx context.Context, in *AuthRequestByEmailCode, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_GenerateTokenByEmailCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	// 用户名密码登录
	GenerateTokenByName(context.Context, *AuthRequestByName) (*AuthResponse, error)
	// 邮箱密码登录
	GenerateTokenByEmail(context.Context, *AuthRequestByEmail) (*AuthResponse, error)
	// 邮箱验证码登录
	GenerateTokenByEmailCode(context.Context, *AuthRequestByEmailCode) (*AuthResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) GenerateTokenByName(context.Context, *AuthRequestByName) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateTokenByName not implemented")
}
func (UnimplementedAuthServiceServer) GenerateTokenByEmail(context.Context, *AuthRequestByEmail) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateTokenByEmail not implemented")
}
func (UnimplementedAuthServiceServer) GenerateTokenByEmailCode(context.Context, *AuthRequestByEmailCode) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateTokenByEmailCode not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_GenerateTokenByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestByName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateTokenByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GenerateTokenByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateTokenByName(ctx, req.(*AuthRequestByName))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GenerateTokenByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestByEmail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateTokenByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GenerateTokenByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateTokenByEmail(ctx, req.(*AuthRequestByEmail))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GenerateTokenByEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestByEmailCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateTokenByEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GenerateTokenByEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateTokenByEmailCode(ctx, req.(*AuthRequestByEmailCode))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateTokenByName",
			Handler:    _AuthService_GenerateTokenByName_Handler,
		},
		{
			MethodName: "GenerateTokenByEmail",
			Handler:    _AuthService_GenerateTokenByEmail_Handler,
		},
		{
			MethodName: "GenerateTokenByEmailCode",
			Handler:    _AuthService_GenerateTokenByEmailCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_service/auth_rpc.proto",
}
